insert into users(name, lastName, age, role_id) values('Ilia', 'Shaidurov', 27, 1);
insert into users(name, lastName, age, role_id) values('Julia', 'Krasnova', 23, 2);
insert into users(name, lastName, age, role_id) values('Olga', 'Ivanova', 22, 3);
insert into role(nameRole) values('Роль № 1');
insert into role(nameRole) values('Роль № 2');
insert into role(nameRole) values('Роль № 3');
insert into prevelege(namePrevelege) values('Право № 1');
insert into prevelege(namePrevelege) values('Право № 2');
insert into prevelege(namePrevelege) values('Право № 3');
insert into prevelege_role(role_id, prevelege_id) values(1, 1);
insert into prevelege_role(role_id, prevelege_id) values(2, 3);
insert into prevelege_role(role_id, prevelege_id) values(3, 2);
insert into state(status) values('Подключен');
insert into state(status) values('Остановлен');
insert into state(status) values('В разработке');
insert into comments(textComments, item_id) values('Высший приоритет', 1);
insert into comments(textComments, item_id) values('Средний приоритет', 2);
insert into comments(textComments, item_id) values('Низкий приоритет', 3);
insert into cotegory(name) values('В работе');
insert into cotegory(name) values('Редактировать');
insert into cotegory(name) values('Не разрабатывается');
insert into attachs(nameFile, size, item_id) values('Первый элемент', 21, 2);
insert into attachs(nameFile, size, item_id) values('Второй элемент', 17, 3);
insert into attachs(nameFile, size, item_id) values('Третий элемент', 5, 1);
insert into item(textItem, users_id, category_id, state_id) values('first_item',1, 3, 2);
insert into item(textItem, users_id, category_id, state_id) values('second_item', 3, 2, 1);
insert into item(textItem, users_id, category_id, state_id) values('third_item', 2, 1, 3);